---
title: "R markdown page with bootstrap 4"
author: "Danielle J. Navarro"
date: "12/08/2021"
output: 
  html_document:
    theme:
      version: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE}
library(bs4cards)

locate_thumbnail <- function(x) {
  system.file("extdata", "thumbnail", paste0(x, ".jpg"), package = "bs4cards")
} 
locate_gallery <- function(x) {
  paste0("https://art.djnavarro.net/gallery/", x)
}

galleries %>% 
  cards(
    title = long_name,
    text = date,
    link = locate_gallery(short_name),
    image = locate_thumbnail(short_name),
    width = "medium",
    layout = "label-below"
  )
```


## Vertical layouts

```{r}
galleries %>% 
  cards(
    title = long_name,
    link = locate_gallery(short_name),
    image = locate_thumbnail(short_name),
    footer = paste("posted on", date),
    width = "wide",
    layout = "label-above"
  )
```


```{r}
galleries %>% 
  cards(
    title = long_name,
    link = locate_gallery(short_name),
    image = locate_thumbnail(short_name),
    text = blurb,
    footer = paste("posted on", date),
    width = "wide",
    layout = "label-below"
  )
```


## Horizontal layouts

```{r}
galleries %>% 
  cards(
    title = long_name,
    text = blurb,
    link = locate_gallery(short_name),
    image = locate_thumbnail(short_name),
    width = "very-wide",
    layout = "label-left"
  )
```


```{r}
galleries %>% 
  cards(
    title = long_name,
    text = blurb,
    link = locate_gallery(short_name),
    image = locate_thumbnail(short_name),
    width = "very-wide",
    footer = paste("posted on", date),
    layout = "label-right",
    breakpoint = 7/12
  )
```



## Inset layouts

```{r}
galleries %>% 
  cards(
    title = long_name,
    link = locate_gallery(short_name),
    image = locate_thumbnail(short_name),
    width = "wide",
    layout = "inset-top", 
    colour = "#ffffffcc"
  )
```


```{r}
galleries %>% 
  cards(
    title = long_name,
    link = locate_gallery(short_name),
    image = locate_thumbnail(short_name),
    width = "wide",
    layout = "inset-bottom", 
    colour = "#ffffffcc", 
    rounding = 0
  )
```


```{r}
galleries %>% 
  cards(
    title = long_name,
    footer = blurb,
    link = locate_gallery(short_name),
    image = locate_thumbnail(short_name),
    width = "wide",
    layout = "inset-bottom", 
    colour = "#ffffffcc"
  )
```


```{r}
galleries %>% 
  cards(
    title = long_name,
    text = blurb,
    footer = date,
    link = locate_gallery(short_name),
    image = locate_thumbnail(short_name),
    width = "wide",
    layout = "inset-bottom", 
    breakpoint = .5,
    colour = "#ffffffcc"
  )
```


## Tags

```{r}
galleries %>% 
  cards(
    title = long_name,
    text = blurb,
    link = locate_gallery(short_name),
    image = locate_thumbnail(short_name),
    tags = tags,
    width = "very-wide",
    footer = tags,
    layout = "label-right",
    breakpoint = 7/12
  )

